## __Creating an Array in NumPy__
Array can either be vector or matrice. A vector is one dimensional array, and a matrix is a two or more dimensional array.

In [2]:
import numpy as np
## Creating a simple 1 dimensional array: vector
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
## Creating 2 dimensional array: matrix

np.array([(1,2,3,4,5), (6,7,8,9,10)])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
## Creating an array from a list

num_list = [1,2,3,4,5]

np.array(num_list)

array([1, 2, 3, 4, 5])

In [7]:
print(np.array(num_list))

[1 2 3 4 5]


__Generating Array__\
NumPy offers various options to generate an array depending on particular need, such as:

* Generating identity array
* Generating zero array of a given size
* Generating ones array with a given size
* Generating an array in a given range
* Generating an array with random values

In [17]:
## Generating an identity array 

identity_array = np.identity(4)
print(identity_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
## Generating an identity matrix of 1s

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
# You can multiply with any constant

np.eye(4) * 7

array([[7., 0., 0., 0.],
       [0., 7., 0., 0.],
       [0., 0., 7., 0.],
       [0., 0., 0., 7.]])

In [19]:
# Generating zero array of a given size
# 1 dimensional zero array
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
# Creating two dimensional array: pass the tuple of rows and columns' number
#np.zeros((rows, columns))

np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
# Generating ones array of a given size
# 1 dimensional one array

np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
# Creating two dimensional ones array: pass the tuple of rows and columns' number
# np.ones((rows, columns))

np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [23]:
## Generating an array in a given range or interval

np.arange(0,5)

array([0, 1, 2, 3, 4])

In [24]:
## If you want to control the step size

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
## You can also use linspace to generate an evenly spaced numbers in a given interval

np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [27]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [28]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [30]:
## Generating an array with random values
# Create a 1D array with 4 random numbers

np.random.rand(4)

array([0.34328344, 0.41635852, 0.18082708, 0.3727411 ])

In [31]:
np.random.rand(4,5)

array([[0.66605898, 0.38211072, 0.30319226, 0.34647672, 0.74564083],
       [0.06240355, 0.25599231, 0.90525629, 0.66581186, 0.31616758],
       [0.38300832, 0.00481535, 0.41739064, 0.03492837, 0.19864991],
       [0.61847793, 0.6390939 , 0.89441247, 0.71407219, 0.06289322]])

In [32]:
### Generate one random integer in a given range

np.random.randint(5,50)

7

In [33]:
### Generate 10 random integers in a given range

np.random.randint(5,50,10)

array([ 6, 14, 29, 46, 42, 13, 30,  5, 47, 41])

In [36]:
## Random see to output the same random vaues at all run time 
import random

random.seed(10)

random.randint(5,50)

41