## __Data Selection: Indexing and slicing an Array__
*Indexing:* Selecting individual elements from the array\
*Slicing:* Selecting group of element from the array.

__1D Array Indexing and Selection__

In [1]:
import numpy as np
# Creating a 1 dimensional vector

array_1d = np.array([1,2,3,4,5])

In [3]:
## Indexing: selcting an element from an array

array_1d[1] , array_1d [-1]

(np.int64(2), np.int64(5))

In [6]:
# Slicing: Returning the group of element from an array, 
# here 4th index is excludes, mean till before 4th index

print(array_1d [2:4])

[3 4]


__2D Array Indexing and Selection__

In [7]:
## Indexing 2D array

array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
## Selecting individual element
## array_2d[row][column]
## let's select 5..that is row 1, column 1 (we start from 0!!)

array_2d[1][1]

np.int64(5)

In [9]:
# let's select 7..that is row 2, column 0

array_2d[2][0]

np.int64(7)

In [10]:
## Selecting whole row
#array_2d[row]

array_2d[1]

array([4, 5, 6])

In [16]:
## Selecting group of elements in 2D array
## array_2d[rows, columns]..You select rows and columns

## Let's select the first two rows
## Rows :2 denotes that we are selecting all rows up to the second. 
## Columns : denotes that all columns are selected.


array_2d[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
## Selecting all first two rows and first two columns

array_2d[:2,0:2]

array([[1, 2],
       [4, 5]])

In [19]:
## Above is same as

array_2d[0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
## This will return all rows, and so all columns and so same as orginal array
array_2d[0:3,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
## return the second row

array_2d[2,:]

array([7, 8, 9])

In [22]:
## return the second column

array_2d[:,2]

array([3, 6, 9])

In [23]:
## return the last two columns

array_2d[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [24]:
## return the first column

array_2d[:,0]

array([1, 4, 7])

In [25]:
## return the first row

array_2d[0,:]

array([1, 2, 3])

Indexing or selecting 2D array may seems confusing but when you try it multiple times, you get the idea. If you are selecting an entire row, that means the all the columns are selected (but not their all values). And vice versa.

As shown below, we are selecting the first row, but as you can see all columns are selected (:).

`array_2d[0,:]`

__Conditional selection__\
You can use a condition to select values in an array. Let's use comparison operators to select the values.

In [26]:
## Let's create an array

arr= np.array(([1,2,3],[4,5,6],[7,8,9]))

In [27]:
## Select all elements in an array which are less than 6

arr[arr <6 ]

array([1, 2, 3, 4, 5])

In [28]:
## Select all elements in an array which are greater than 6

arr[arr > 6]

array([7, 8, 9])

In [29]:
## Select all even numbers in an array

arr[arr % 2 ==0 ]

array([2, 4, 6, 8])

In [30]:
## Select all odd numbers in an array

arr[arr % 2 !=0 ]

array([1, 3, 5, 7, 9])

In [31]:
## You can also have multiple conditions

## In all odd numbers, return values which are greater or equal to 5


arr[(arr % 2 !=0 ) & (arr >=5) ]

array([5, 7, 9])

In [32]:
## Using logical selection, you can also return True for values in which 
# a given condition is met in an array

arr > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [33]:
## We do not have 0 in our array

arr == 0

array([[False, False, False],
       [False, False, False],
       [False, False, False]])