## __Basic Array Operations__
Quick Arithmetic operation: Addition, Subtraction, Multiplication, Division, Squaring

In [18]:
import numpy as np
# Let's create two arrays

arr1 = np.arange(0,5) # i.e. [0, 1, 2, 3, 4]
arr2 = np.arange(6,11) # i.e. [6, 7, 8, 9, 10]

In [19]:
## Addition

arr1 + arr2

## Subtraction

arr2 - arr1

## Multiplication

arr1 * arr2

## Division

arr1 / arr2

## Squaring

arr1 ** 2

print(f'Addition : {arr1 + arr2}\nSubtraction: {arr2 - arr1}\nMultiplication: {arr1 * arr2}\nDivision: {arr1 / arr2}\nSquaring: {arr1**2}')

Addition : [ 6  8 10 12 14]
Subtraction: [6 6 6 6 6]
Multiplication: [ 0  7 16 27 40]
Division: [0.         0.14285714 0.25       0.33333333 0.4       ]
Squaring: [ 0  1  4  9 16]


__Universal functions__\
NumPy universal functions (`ufunc`) allows to compute math, trigonometric, logical and comparison operations such as sin, cos, tan, exponent(exp), log, square, greater, less, etc...

In [14]:
## creating two arrays 

arr1 = np.arange(0,5)
arr2 = np.arange(6,11)

In [15]:
## Calculating the sum of two arrays

np.add(arr1, arr2)

array([ 6,  8, 10, 12, 14])

In [16]:
## Calculating the product of two arrays

np.multiply(arr1, arr2)

array([ 0,  7, 16, 27, 40])

In [17]:
## Calculating the difference between two arrays

np.subtract(arr1, arr2)

array([-6, -6, -6, -6, -6])

In [20]:
## Calculating the division of two arrays

np.divide(arr1, arr2)

array([0.        , 0.14285714, 0.25      , 0.33333333, 0.4       ])

In [21]:
## Calculating the sin of arr1

np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [22]:
np.sin([0,45,90,180])

array([ 0.        ,  0.85090352,  0.89399666, -0.80115264])

In [23]:
## Calculating the cosine of arr 1

np.cos(arr1)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [24]:
np.cos([0,45,90,180])

array([ 1.        ,  0.52532199, -0.44807362, -0.59846007])

In [25]:
## Calculating the tangent(tan) of the array

np.tan(arr2)

array([-0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

In [26]:
## Calculating the logarithmic(log) and exponent(exp or e^) of the array
np.log(arr2),np.exp(arr2)

(array([1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]),
 array([  403.42879349,  1096.63315843,  2980.95798704,  8103.08392758,
        22026.46579481]))

In [27]:
## Calculating the power  of the array
## Array 1 is powered array 2...0^6=0, 1^7=1, 2^8=256, etc..

np.power(arr1, arr2)

array([      0,       1,     256,   19683, 1048576])

In [28]:
## Comparison operations return true or false
## Arr 1 is less than arr 2...so that's false

np.greater(arr1, arr2)

array([False, False, False, False, False])

In [29]:
## Comparison operations return true or false
## Arr 1 is less than arr 2...so that's true

np.less(arr1, arr2)

array([ True,  True,  True,  True,  True])