## __Basic Statistics__
With NumPy, we can compute the basic statistics such as the standard deviation (`std`), variance (`var`),mean, median, minimum value, maximum value of an array.

In [1]:
import numpy as np
## Creating an array 

arr = np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

__Standard Deviation__

In [2]:
## calculating the standard deviation of the array
## Std is how much an element of the array deviates from the mean of the array

np.std(arr)


np.float64(1.4142135623730951)

In [3]:
arr2 = np.array([[3,4], [5,6]])

np.std(arr2)

np.float64(1.118033988749895)

In [4]:
## Specifying the axis
## By default, the std is computed on the flattened values (or converted into a single column vector)

np.std(arr2, axis=0)

array([1., 1.])

In [5]:
np.std(arr2, axis=1)

array([0.5, 0.5])

__Variance__

In [7]:
## Calculating the Variance (var)

arr = np.arange(0,5)

np.var(arr), np.var(arr2)

(np.float64(2.0), np.float64(1.25))

__Mean__

In [8]:
## Calculating the mean of the array

np.mean(arr)

np.float64(2.0)

In [9]:
## mean gives the same results as the average
np.average(arr)

np.float64(2.0)

__Median__

In [10]:
## Calculating the median of the array

np.median(arr)

np.float64(2.0)

__Minimum and Maximum__

In [11]:
## Calculating the minimum and max value

np.min(arr), np.max(arr)

(np.int64(0), np.int64(4))