## __Data Manipulation__
Data Manipulation is important step in Machine Learning project. Let's some of NumPy methods and functions which are useful in data manipulation.

__Shape of the array__

In [26]:
import numpy as np
## Creating an array 

arr1 = np.arange(0,10)
arr2 = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [27]:
arr1, arr2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [28]:
np.shape(arr1), np.shape(arr2), arr2.shape


((10,), (3, 3), (3, 3))

__Shaping the Array__\
`np.reshape(array_name, newshape=(rows, columns)` or `array_name.reshape(rows, columns)` change the shape of the array. The rows and columns of the new shape has to comform with the existing data of the array. Otherwise, it won't work. Take an example, you can convert (3,3) array into (1,9) but you can't convert it into (5,5).

In [29]:
### arr1 is (10,)....10 rows, 1 column. Let's reshape it into (5,2)
np.reshape(arr1, shape=(5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [30]:
## This would also work
arr1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [31]:
arr2_reshaped = arr2.reshape(9,1)
arr2_reshaped.T

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [32]:
arr2_reshaped.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
## np.resize can also be used to change the shape of the array into a specific size

np.resize(arr2, (1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

__Copying array__

In [34]:
arr1 = np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr1_copy = arr1.copy()
arr1_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
## Copying the values of one array into the other 

## Let's copy array 2 into 1 --they have the same shape

arr1 = np.arange(0,6)
arr2 = np.arange(6,12)

In [37]:
## arr1 is destination, arr2 is source
np.copyto(arr1, arr2)

In [38]:
arr1

array([ 6,  7,  8,  9, 10, 11])

__Joining arrays__

In [39]:
### Creating two arrays

arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[10,11,12]])

In [40]:
np.concatenate((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
## Transposing arr2
## arr2.T is transpose operation

np.concatenate((arr1, arr2.T), axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [42]:
### Setting axis to none flatten the array

np.concatenate((arr1, arr2), axis=None)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [43]:
### Joining two 1Ds array into 2D array: Stacking

# Column stacking

arr1 = np.arange(0,6)
arr2 = np.arange(6,12)

np.column_stack((arr1, arr2))

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [44]:
## Row stacking 

np.vstack((arr1, arr2))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

__Splitting arrays__

In [45]:
arr1 = np.arange(0,6)
arr1

array([0, 1, 2, 3, 4, 5])

In [46]:
### Splitting the array into two arrays

np.split(arr1, 2)

[array([0, 1, 2]), array([3, 4, 5])]

In [47]:
### Splitting the array into three arrays

np.split(arr1, 3)

[array([0, 1]), array([2, 3]), array([4, 5])]

__Adding and repeating elements in an array__

In [48]:
arr1 = np.arange(0,6)
arr1

array([0, 1, 2, 3, 4, 5])

In [49]:
## Adding the values at the end of the array
np.append(arr1,7)

array([0, 1, 2, 3, 4, 5, 7])

In [50]:
### Given an array, can you add itself multiple times? or repeat it?

arr = np.array([[1,2,3]])
np.tile(arr, 3)

array([[1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [51]:
np.repeat(arr,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

__Sorting elements in an array__

In [52]:
arr = np.array([[1,2,3,4,5,3,2,1,3,5,6,7,7,5,9,5]])

np.sort(arr)

array([[1, 1, 2, 2, 3, 3, 3, 4, 5, 5, 5, 5, 6, 7, 7, 9]])

In [53]:
## Finding the unique elements in an array

arr = np.array([[1,2,3,4,5,3,2,1,3,5,6,7,7,5,9,5]])

np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7, 9])

__Reversing an array__

In [54]:
## You can also flip the array

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
## Up/down flipping

np.flipud(arr)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [56]:
## left/right flipping

np.fliplr(arr)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])